/* eslint-disable @typescript-eslint/no-require-imports */
/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */

/* 색 값은 src/styles/tokens.css에만 두고 이 파일은 역할형 utility를 매핑한다. */
module.exports = {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        fontFamily: {
            sans: [
                'Pretendard',
                'Pretendard Variable',
                '"Noto Sans KR"',
                'ui-sans-serif',
                'system-ui',
                '-apple-system',
                'BlinkMacSystemFont',
                '"Segoe UI"',
                'Roboto',
                '"Helvetica Neue"',
                'Arial',
                'sans-serif',
                '"Apple Color Emoji"',
                '"Segoe UI Emoji"',
            ],
            mono: [
                'ui-monospace',
                'SFMono-Regular',
                'Menlo',
                'Monaco',
                'Consolas',
                '"Liberation Mono"',
                '"Courier New"',
                'monospace',
            ],
        },
        screens: {
            xs: '576px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1536px',
        },
        extend: {
            colors: {
                'app-canvas': 'var(--app-canvas)',
                'content-surface': 'var(--content-surface)',
                'content-soft': 'var(--content-soft)',
                'content-line': 'var(--content-line)',
                'content-fg': 'var(--content-fg)',
                'content-muted': 'var(--content-muted)',
                'content-subtle': 'var(--content-subtle)',
                chrome: 'var(--chrome-bg)',
                'chrome-strong': 'var(--chrome-bg-strong)',
                'chrome-raised': 'var(--chrome-bg-raised)',
                'chrome-selected': 'var(--chrome-bg-selected)',
                'chrome-fg': 'var(--chrome-fg)',
                'chrome-muted': 'var(--chrome-muted)',
                'on-strong': 'var(--on-strong)',
                'control-action': 'var(--control-action)',
                'control-action-hover': 'var(--control-action-hover)',
                'control-action-soft': 'var(--control-action-soft)',
                'control-action-ink': 'var(--control-action-ink)',
                'control-focus': 'var(--control-focus)',
                'control-focus-on-dark': 'var(--control-focus-on-dark)',
                'brand-structure': 'var(--brand-structure)',
                'brand-highlight': 'var(--brand-highlight)',
                'brand-highlight-bright': 'var(--brand-highlight-bright)',
                'brand-highlight-deep': 'var(--brand-highlight-deep)',
                'brand-highlight-soft': 'var(--brand-highlight-soft)',
                /* 소셜 로그인 — 외부 브랜드 규격(재색 금지, design-system §2.8) */
                kakao: 'var(--kakao)',
                naver: 'var(--naver)',
                /* 상태 */
                success: 'var(--success)',
                'success-ink': 'var(--success-ink)',
                'success-soft': 'var(--success-soft)',
                danger: 'var(--danger)',
                'danger-ink': 'var(--danger-ink)',
                'danger-soft': 'var(--danger-soft)',
                warning: 'var(--warning)',
                'warning-soft': 'var(--warning-soft)',
                info: 'var(--info)',
                'info-soft': 'var(--info-soft)',
            },
            fontSize: {
                label: ['11px', '1.4'],
                micro: ['12px', '1.45'],
                body: ['13px', '1.5'],
                value: ['17px', '1.35'],
                figure: ['28px', '1.2'],
                title: ['34px', '1.15'],
                'figure-xl': ['44px', '1.1'],
            },
        },
    },
    plugins: [require('@tailwindcss/typography')],
}
