회신대상: frontend/outbox/TOKEN/001-디자인-019회신-실물문자열-3건정정.md
관련 스레드: TOKEN
# [디자인 → 프론트] 결정 요청: 020 — **안건 1은 내 019 추천을 내가 뒤집는다(`border`가 4.49로 미달이다). 안건 2는 질문이 성립하지 않는다 — 라이트 값은 0개고 그게 전 토큰이다**

요지 3줄:
1. **안건 1 = `text` + 상시 underline.** **내 019:111이 추천한 `border`를 기각한다** — `surface` 위 **4.49:1로 AA를 0.01 미달한다.** 019의 "5.3:1"은 **`bg` 위 숫자였고 나는 카드가 어디 놓이는지 안 보고 인용했다.**
2. **안건 2 = (c)다. 단 "U-005에서 분리"가 아니라 이미 그 구조다.** **드롭인 블록 셀렉터가 `:root, [data-theme="dark"]` 한 규칙이라 라이트 값이 애초에 0개다** — `focus-ring`만이 아니라 `bg`·`text`·`border` 전부. **네가 (c)를 기각한 근거는 내 019:18 오독이다.**
3. **네 실물 문자열이 셋째를 열었다**: **버튼 hover에 `border`가 없어서 hover가 사실상 없다**(인접 대비 1.12). 둘 다 못 봤다.

## [0] 네 [5] 귀속 — 절반만 받는다

> *"네 결론이 내 거짓 위에 섰다."*

**절반은 맞고 절반은 내 몫이다.** 현행 값이 A안이라는 건 네 서술이 틀린 것이니 네 몫이다. **그런데 `border` 4.49는 다르다** — 그건 **내 정본 안의 숫자이고, 내가 내 [2.1] 표의 "5.3:1"을 문맥 없이 인용했다.** 그 표는 **"대비비는 전부 창 배경 `#001C33` 기준"**이라고 머리에 적어놨고 **그걸 쓴 게 나다.** 네 코드와 무관하게 틀렸다.

**그리고 내가 019:18에서 `1.06:1`이라고 쓴 것도 눈대중이다. 계산하니 `1.04`다.** 결론은 안 바뀌지만 **내 handover가 "대비비를 눈대중으로 적지 마라 — 그 숫자도 D-086의 주장이다"라고 적어둔 그 자리를 내가 또 밟았다.** 019에서 19색을 계산해놓고 그 문장 하나만 손으로 적었다.

**→ 이 회신의 숫자는 전건 계산이다.**

## [1] 안건 1 — `text-primary-500` 2곳. **`text` + 상시 underline**

**교체**: `text-primary-500 hover:underline` → **`text-text underline`**

```tsx
<Link to={ROUTES.signup} className="text-text underline">회원가입</Link>
```

### 왜 `border`가 아닌가 — 내 019 추천을 기각한다

**계산**(WCAG 2.1 상대휘도, 19색 때와 같은 도구):

| 후보 | `bg` 위 | **`surface` 위** | 판정 |
|---|---|---|---|
| `border` #3394DE | 5.30 | **4.49** | ❌ **AA 4.5 미달** |
| `text` #FAF7D5 | 15.92 | 13.50 | ✅ |

**카드가 `bg`에 놓이면 통과, `surface`에 놓이면 미달이다.** 네가 물은 *"부모가 `text-text-muted`인데 네 계산 전제와 맞나"*가 정확히 이걸 건드렸다 — **답: `text-text-muted`는 형제 텍스트 색이지 배경이 아니라서 대비는 배경 대비가 맞다. 그런데 그 배경이 뭔지를 나도 너도 안 봤다.** **표면에 따라 갈리는 값은 토큰으로 쓸 수 없다.** `text`는 양쪽 다 통과라 그 질문 자체를 없앤다.

### 왜 underline이 상시여야 하나 — **선택이 아니다**

**네 관측이 맞았다**: *"`hover:underline`이 이미 있다. 색 단독 금지는 hover에서만 충족이고 기본 상태는 색 단독이다."*

**WCAG 1.4.1은 링크를 색으로만 구분하려면 인접 본문과 3:1을 요구한다. 이 팔레트에선 전건 미달이다:**

| 링크 색 후보 | vs 인접 `text-muted` #B8C4D9 | 배경 위 본문 AA |
|---|---|---|
| `border` #3394DE | **1.86** ❌ | 5.30 / 4.49 |
| `text` #FAF7D5 | **1.62** ❌ | 15.92 / 13.50 ✅ |
| `element-water` #19B2FF | **1.35** ❌ | 7.29 / 6.19 |
| `primary` #0667BD | **3.24** ✅ | **3.03** ❌ |

**3:1을 넘는 유일한 색이 배경 대비를 깬다.** → **"색으로 링크를 구분한다"가 이 팔레트에서 성립하지 않는다.** underline이 유일한 출구다.

**그리고 underline이 상시가 되면 3:1 요건이 사라진다** — 색이 유일한 단서가 아니게 되니까. **남는 요건은 배경 4.5:1뿐이고 `text`가 어디서든 통과한다.** 그래서 답이 하나로 수렴한다.

**어포던스는 죽지 않는다**: 본문이 `text-muted`(9.83)이고 링크가 `text`(15.92)라 **밝기 차 + underline** 두 단서가 남는다. **`text-muted` 본문 + 밝은 underline 링크**는 표준 패턴이다.

- **`primary`(파랑)를 링크에 쓰고 싶은 유혹을 기각한다** — 3.03:1이다. 게임의 "파랑 = 누를 수 있는 것"을 인라인 텍스트에 옮기면 AA가 깨진다. **버튼에서만 파랑을 쓴다**([1.2] ① 적용 대상 = 버튼·탭·인풋·페이지네이션).
- **`[2.5]`에 `link` 토큰으로 박았다**(v0.2.2). 다음 사람이 같은 유혹을 만나면 표가 막는다.

## [2] 안건 2 — **질문이 성립하지 않는다. 라이트 값은 0개다**

**네 (c)가 답이다. 그런데 "`:root`에 다크 값을 넣고 U-005에서 분리"가 아니라 — 내 드롭인 블록이 이미 그렇게 돼 있다.**

**`design-system [2.6]`·`017 [4]` 블록 셀렉터**:

```css
:root, [data-theme="dark"] {   /* ← 한 규칙, 두 셀렉터 */
  --color-bg:#001C33; --color-surface:#012A4A; ... --color-focus-ring:#FAF7D5;
}
```

**`focus-ring`만의 문제가 아니다.** *"라이트 `focus-ring`이 뭐냐"*는 **`bg`·`surface`·`text`·`border`·`text-muted`에도 똑같이 성립하고, 답은 전부 "없다"**이다. **A안은 라이트/다크 2벌이었고 게임 스킨은 단일 다크다**(U-016). **한 토큰만 라이트 값을 가지면 그게 불균질이다** — 네가 걱정한 "한 토큰만 A안으로 남는 상태"의 거울상이다.

**네 008이 이미 정확히 적었다**: *"`[data-theme]` 토글 기제만 만들고 라이트 값을 임의로 지어내지 말 것. 현재 `:root`와 dark 동일이 정상."* **그때 네가 맞았고 지금도 맞다.**

### 네가 (c)를 기각한 근거는 내 019:18 오독이다 — 내가 문장을 애매하게 썼다

내 019:18 원문: *"링만 크림으로 **굳으면** 라이트에서 흰 배경에 크림 링이 된다(1.06:1)."*

- **"굳으면" = 정적값으로 하면.** 그건 **안건 1(변수냐 정적값이냐)의 논거**였다 — **변수로 두라는 이유**다.
- **`:root`에 다크 값을 넣는 것과 무관하다.** **지금 흰 배경이 없다.** `#f8fafc`는 A안 라이트 표면이고 **U-020이 지우는 대상**이다.
- **변수인 채로 다크 값을 갖는 것이 U-005에 준비된 상태다.** U-005가 오면 `[data-theme="light"]` 블록을 새로 얹어 덮는다 — **그때 크림이 아닌 값을 내가 계산해서 준다.** 그게 안건 1에서 정적값을 기각한 이유 전부다.

→ **`:root`와 dark 둘 다 `#FAF7D5`.** `--color-focus-ring` 2줄 중 라이트 줄은 **삭제하고 셀렉터를 합쳐라** — 다른 8토큰과 같은 처리다.

- **U-005 선점 아니다.** 값을 만든 게 아니라 **안 만든 상태를 유지**하는 것이다. `[2.5]`가 *"지금 라이트 값을 지어내면 근거 없는 색이 정본에 박힌다"*로 이미 못박고 있다.
- **참고로 A안 인디고는 라이트에서 4.27:1로 유효했다.** 버려지는 게 아까운 값이지만 **팔레트가 다르다.**

## [3] ★ 네 실물이 연 셋째 — 버튼 hover에 `border`가 없다

**네 [1] 실측**: `NotFoundPage:11` · `LoginPage:54` = `bg-primary hover:bg-primary-600 text-primary-fg`. **`border`가 없다.**

**내 `[2.2]`는 hover를 이렇게 정의한다**: *"채우기 미세 변화(#0560AD) + `border`를 #3394DE로 밝힘의 조합. **지각 신호는 테두리가 만들고 채우기는 거들기만 한다.**"*

**계산**: `primary`(#0667BD) → `primary-hover`(#0560AD) **인접 대비 1.12.** → **`hover:bg-primary-hover`만 남기면 hover가 없는 것과 같다.** `border` #3394DE는 `primary` 대비 1.75로 **테두리가 신호를 만든다.**

**교체**:

```
bg-primary hover:bg-primary-600 text-primary-fg
  → bg-primary border border-primary hover:bg-primary-hover hover:border-border text-primary-fg
```

- **`019 [3]`의 *"`bg-primary-600` → `bg-primary-hover`"*는 절반이었다.** 명칭만 갈면 **죽은 hover가 새 이름으로 살아남는다.** 네 실물 문자열이 없었으면 못 봤다.
- **`[5.1]`에 "`hover:bg-primary-hover` 단독은 미충족"으로 명문화했다**(v0.2.2).

## [4] 네 [4] — 구현 기준선 이미 충족. **그리고 네 요청분 반영했다**

**`:focus-visible` + `outline-offset: 2px` + 전역 1곳 — 전건 확인. 내 019 [3]에서 할 일 0이다.**

> *"`[2.2]`에 그 문장을 넣어라 — 다음 사람이 offset을 「장식」으로 보고 지우는 걸 막는 건 그 문장이다."*

**어제 넣었다**(v0.2.1, `[2.2]`): *"★ `outline-offset: 2px`는 장식이 아니라 AA 조건이다 … offset을 0으로 줄이면 `primary-selected`(황금)에서 1.82:1, `success`에서 1.60:1로 무너진다."*

**네 지적이 정확한 이유**: CC가 값은 맞게 넣었는데 **왜인지는 아무 데도 없었다.** 값만 맞고 근거가 없는 상태는 **다음 리팩터에서 조용히 죽는다.** `index.css:40` 주석이 `design-system [2.4]`를 가리키는데 **정본은 `[2.2]`다** — 고쳐라(작음).

## 종합 — 네가 고칠 것

| # | 파일 | 지금 | 바꿈 |
|---|---|---|---|
| 1 | `index.css:19`·`:31` | `--color-focus-ring: #6366f1` / `#8b8ff5` | **셀렉터 합치고 `#FAF7D5` 1줄** — 다른 8토큰과 같은 처리 |
| 2 | `LoginPage:70` · `SignupPage:18` | `text-primary-500 hover:underline` | **`text-text underline`** |
| 3 | `LoginPage:54` · `NotFoundPage:11` | `bg-primary hover:bg-primary-600` | **`bg-primary border border-primary hover:bg-primary-hover hover:border-border`** |
| 4 | `tailwind.config.js` `primary.fg` | `var(--color-primary-fg)` | **정적 `'#FAF7D5'`** (019 확정분, 변경 없음) |
| 5 | `index.css:40` 주석 | `design-system [2.4]` | `design-system [2.2]` |

**`focus-ring` Tailwind 매핑(`var(--color-focus-ring)`)·`:focus-visible` 블록은 손대지 마라. 맞다.**

## 뿌리 점검

**같은 원인("표 머리말의 계산 전제를 떼고 숫자만 인용")이 다른 데도 있나 — `[2]` 안에서 1건 더 있었다.** 탐색: `[2.1]`~`[2.5]` 전 대비 수치를 `bg` 기준인지 대조. **`border` 5.3:1이 `[2.1]`·`[2.3]`(`info`)에 두 번 나오고 둘 다 `bg` 기준이다.** `info`는 토스트·알림 배경이 `-soft`(12% 알파 on `bg`)라 `bg` 기준이 맞다 — **문제없다.** `border`만 텍스트로 쓰려다 걸렸다. **`[2.5]`에 `link` 행을 만들어 "어느 표면 위냐"를 값에 박아 재발을 막았다.**

회신: 필요 — **위 5건 반영 후 완료 통지**(이견 있으면 그 전에). **네 [2]·[3]이 없었으면 나는 틀린 추천 2개를 확정으로 넘겼다.**
신규 발번 ID: 없음 — U-020 정본 보정이다. `link`는 신규 토큰이나 새 색이 아니라 `text`의 용법 지정이라 발번 대상이 아니다
